# router swap identifier, must have prefix 'routerswap'
Identifier = "routerswap-test"
# router swap type (eg. erc20swap, nftswap, anycallswap)
SwapType = "erc20swap"
# default subtype is empty. anycall has subtype of 'curve'
SwapSubType = ""

# modgodb database connection config
[Server.MongoDB]
DBName = ""
DBURLs = [""]
Password = ""
UserName = ""

# bridge API service
[Server.APIServer]
# listen port
Port = 11556

# OnChain config
[OnChain]
APIAddress = [""]
Contract = ""

# Gateways config. key is chainID
[Gateways]
1660545256757 = [""]
4 = [""]

# MPC config
[MPC]
# use private key instead (use for testing)
SignWithPrivateKey = true

# set signer's private key, key is chain ID (use for testing)
[MPC.SignerPrivateKeys]
1660545256757 = ""
4 = ""
